### ISSUE TITLE
Redundant code?

### ISSUE THREAD

**Issue by heshamMassoud** [mendhak/Gradle-Travis-Colored-Output#2]
I am wondering what's the purpose of these two checks:
https://github.com/mendhak/Gradle-Travis-Colored-Output/blob/c187f35dd306f68c50234452d34cde1838f12628/ColoredOutput.gradle#L52-L53

When it's either way with these colors set in the lines just before?

**Comment by mendhak** [comment]
Really can't remember now, definitely looks redundant..  Could you try removing those lines you've highlighted, try running passing + failing builds again to see if anything happens?

**Comment by heshamMassoud** [comment]
@mendhak I have them removed in the project where I am using the script. Tried running successful and failure tests. And seems fine.

**Comment by heshamMassoud** [comment]
Thanks for writing the script btw :)
