### ISSUE TITLE
Project does not have an explicit license

### ISSUE THREAD

**Issue by ob-stripe** [mendhak/Gradle-Travis-Colored-Output#4]
Hi @mendhak, thanks for this neat script! I'm interested in using it for [Stripe's Java library](https://github.com/stripe/stripe-java), however your project currently does not have an explicit license. Would you consider releasing your code under an open-source license?

**Comment by mendhak** [comment]
Oops that's a mistake, thanks for spotting it. I should have added one.  I'll try to add one soon.

**Comment by mendhak** [comment]
OK - how is this does this look fine? 

https://github.com/mendhak/Gradle-Travis-Colored-Output/blob/master/LICENSE

**Comment by ob-stripe** [comment]
Awesome! Thanks for the quick response :) Keep up the good work!
